--- #YAML:1.0
name:                Mac-OSVersion
version:             0.14
abstract:            Get the Mac OS X system version
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Mac::Gestalt:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
